# Generated by Django 5.2.12 on 2026-03-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LSN2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='primary_key',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
