# Generated by Django 5.2.12 on 2026-03-27 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LSN2', '0002_remove_user_id_user_primary_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
