# Generated by Django 5.2.12 on 2026-03-28 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LSN2', '0004_module_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Module',
        ),
    ]
